### ISSUE TITLE
With Hugo v0.152.0, getting error: invalid module config for "github.com/google/docsy": "../../node_modules/bootstrap"

### ISSUE THREAD

**Issue by tekezo** [google/docsy#2345]
### Environment

- [x] Version of Docsy you are using: v0.12.0
- [x] How are you using Docsy? As a:
  - [x] Hugo module
- [x] Version of Hugo you are using (output of `hugo version`): hugo v0.152.0+extended+withdeploy darwin/arm64 BuildDate=2025-10-21T16:29:49Z VendorInfo=brew
- [x] OS:
  - [x] macOS

### Problem

With Hugo v0.152.0, I'm getting the following error at running "hugo server".

```
Error: command error: failed to load modules: invalid module config for "github.com/google/docsy": "../../node_modules/bootstrap": mount source must be a local path for modules/themes
```

It seems this is happening because that behavior was disallowed by this PR in Hugo.

- https://github.com/gohugoio/hugo/pull/14071
- https://github.com/gohugoio/hugo/issues/14069

On my end, it started working after I removed the configuration for `Docsy as an NPM package` from hugo.yaml.
https://github.com/google/docsy/blob/main/hugo.yaml#L39-L44

**Comment by fabiendelpierre** [comment]
This is happening on Linux as well FWIW (predictably). Working around it for now by capping the version of Hugo to v0.151.2 in my builds.

**Comment by tekezo** [comment]
In Hugo v0.152.0 the minifier was also updated, and with tdewolff/minify v2.24.4, Popper's positioning code breaks. As a result, production builds with Hugo v0.152.0 cause popovers to render in the wrong place. (I haven't investigated this deeply)
So, I've also reverted to Hugo v0.151.2 for now.

**Comment by marshalc** [comment]
For the purposes of linking up, my posting about this build issue on the Hugo forum led to this Issue being logged there: https://github.com/gohugoio/hugo/issues/14083

**Comment by jmooring** [comment]
@tekezo ~~What does "Popper's positioning code breaks" mean?~~

See:
- <https://github.com/gohugoio/hugo/issues/14086>.
- <https://github.com/tdewolff/minify/issues/863>

**Comment by tekezo** [comment]
@jmooring  Thank you. The Popper issue I encountered is exactly the same as the one you reported. The popover always appears at the origin of the browser window.

**Comment by jmooring** [comment]
Both of the problems described above have been addressed with [v0.152.2](https://github.com/gohugoio/hugo/releases/tag/v0.152.2).

**Comment by chalin** [comment]
Thanks all! @tekezo - can you confirm whether any issues persist when using [v0.152.2](https://github.com/gohugoio/hugo/releases/tag/v0.152.2)? If not, I'll look into as soon as I can. In the meantime, consider ticking to the officially compatible version of Hugo defined for the version of Docsy you are using.

**Comment by fabiendelpierre** [comment]
Speaking for myself, using v0.152.2 has resolved the issue introduced in v0.152.0.

v0.151.2: worked
v0.152.0: broken
v0.152.2: works again like v0.151.2 without changing anything

**Comment by tekezo** [comment]
@jmooring @chalin Thank you!
Both the mount source and minify issues have been successfully resolved in Hugo v0.152.2.
It looks like the built JS is now identical between v0.151.2 and v0.152.2.

**Comment by chalin** [comment]
FYI, Hugo is being updated to 0.152.2 in `main` via #2350.
