### ISSUE TITLE
Github discussions link in page footer

### ISSUE THREAD

**Issue by js-xc** [google/docsy#542]
The link to "Github discussions" in the page footer of docsy's documentation points incorrectly to twitter instead.

**Comment by LisaFC** [comment]
Ah, that's on me. Didn't update the config.toml properly....

**Comment by LisaFC** [comment]
Fixed!

**Comment by js-xc** [comment]
Sorry, it's still not working. The link is now "https//github.com/google/docsy/discussions" (: after https is missing)

**Comment by LisaFC** [comment]
Now actually fixed! Sorry about that.
