### ISSUE TITLE
Error Generating site when using Docsy as a module

### ISSUE THREAD

**Issue by ITblacksheep** [google/docsy#833]
Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): SCSS processing failed: file "stdin", line 6, col 1: File to import not found or unreadable: ../vendor/bootstrap/scss/bootstrap.

**Comment by deining** [comment]
To my dismay I realized that #801 is not valid, module dependencies were inadvertently disabled in the final version that was merged. Sorry for that, I will author a PR that fixes this shortly.

Fortunately, there is a way to work around this. In your `config.toml`, simply add:

```
[[module.imports]]
  path = "github.com/twbs/bootstrap"
  disable = false
[[module.imports.mounts]]
  source = "scss"
  target = "assets/vendor/bootstrap/scss"
[[module.imports]]
  path = "github.com/FortAwesome/Font-Awesome"
[[module.imports.mounts]]
  source = "scss"
  target = "assets/vendor/Font-Awesome/scss"
[[module.imports]]
    path = "github.com/google/docsy"
```

This should get you up and running. Please let me know if this solves your problem.

**Comment by kneyugn** [comment]
Hello! Thanks for working on this. I am also seeing this issue and the copying and pasting the above into the config did not resolve it. Do I need to run any command again? I followed this guide:

https://deploy-preview-802--docsydocs.netlify.app/docs/updating/convert-site-to-module/#work-around-a-known-bug-in-gos-module-management

**Comment by deining** [comment]
> Do I need to run any command again?

To be on the safe side, you can run:

```
hugo mod clean
```

Afterwards, for diagnostic purposes, you may run `hugo mod graph`, which should list 3 module dependencies:

```
$ hugo mod graph
hugo: downloading modules …
hugo: collected modules in 13739 ms
yourModule github.com/twbs/bootstrap@v4.6.1+incompatible
yourModule github.com/FortAwesome/Font-Awesome@v0.0.0-20210804190922-7d3d774145ac
yourModule github.com/google/docsy@v0.0.0-20220114111958-b103aadf9739
```

If you don't see these 3 dependencies, you are in trouble and it won't work.

**Comment by LisaFC** [comment]
This should be fixed in #837, right?

**Comment by kneyugn** [comment]
> This should be fixed in #837, right?

Hello @LisaFC, It isn't resolved for me.

hugo mod graph

<my-module> github.com/twbs/bootstrap@v5.1.3+incompatible
<my-module> github.com/FortAwesome/Font-Awesome@v4.7.0+incompatible
<my-module> github.com/google/docsy@v0.0.0-20220117100953-fbc516e8d1dd

**Comment by deining** [comment]
> hugo mod graph
> 
> < my-module > github.com/twbs/bootstrap@v5.1.3+incompatible

This should be bootstrap@v4.6.1, not @v5.1.3. You pulled in the latest version, that's incorrect.

 < my-module > github.com/FortAwesome/Font-Awesome@v4.7.0+incompatible

This should translate to Font-Awesome@7d3d774145ac, which is 5.15.4. Font-Awesome@v4.7.0 is ways to old.

 < my-module > github.com/google/docsy@v0.0.0-20220117100953-fbc516e8d1dd

This one is correct.

Do you want to convert an existing site or start from scratch?
Module setup worked flawlessly for me, I tried it out this morning without any problems.

If you can't make it work, present error messages or contact me off-list (see github account info).

**Comment by kneyugn** [comment]
Hey @deining, I am getting the same error as above. I am converting an existing project. How do I ensure that my installs have the latest Font-Awesome and Bootstrap. I am not familiar with how go or Hugo modules work.

**Comment by ITblacksheep** [comment]
Ok i am passed the original error but now my site doesn't show anything. It is not understanding the language. I am going to flip back to non module and then see if it still happens.

**Comment by ITblacksheep** [comment]
So when switching back to git submodule I am getting the same issues as #836. The fix for #836 did fix the font awesome issue, but now back to not rendering any content under a lang folder. If i move all the content under content it renders fine, but if i move it into content\en it renders a blank page.

**Comment by huehnerlady** [comment]
With github submodules I have the same problem that I'll get problems with rendering, the sidebar shows a navbar from a different part of the website (blog?) that I am on, the main page is not rendering at all (apart from header)  and some other pages (eg. the blog) are also not rendering. I have the same setup with the language folder

**Comment by ITblacksheep** [comment]
@deining Should we close this out as the original issue has been fixed and open a new one up for the rendering issue?

**Comment by deining** [comment]
> @deining Should we close this out as the original issue has been fixed

Yes, please.

> and open a new one up for the rendering issue?

Again, yes. Can you provide as many details as possible please? Is your project available publicly (github, gitlab, or so) or can we get access to it? Ideally we could reproduce the faulty behaviour locally. That would make it much easier to track it down. Thanks.

**Comment by mattomis** [comment]
this seems to be the issue I am having. This is docsy running in hugo as a container in VS Code with a cloned docsy example repo from my github account. The docsy example repo does not contain a dependencies folder. The following modules generate an error:
```
[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
  [[module.imports]]
    path = "github.com/mattomis/docsy-example"
    disable = false
[[module.imports]]
  path = "github.com/twbs/bootstrap"
  disable = false
[[module.imports.mounts]]
  source = "scss"
  target = "assets/vendor/bootstrap/scss"
[[module.imports]]
  path = "github.com/FortAwesome/Font-Awesome"
[[module.imports.mounts]]
  source = "scss"
  target = "assets/vendor/Font-Awesome/scss"
```

$ hugo mod graph
Error: failed to load modules: module "github.com/FortAwesome/Font-Awesome" not found in "/workspaces/omis_docs_07_23/omis_docs_7_23/themes/github.com/FortAwesome/Font-Awesome"; either add it as a Hugo Module or store it in "/workspaces/omis_docs_07_23/omis_docs_7_23/themes".: module does not exist
